-- +goose Up
CREATE TABLE gateway_sync_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_job_id bigint NOT NULL REFERENCES gateway_sync_jobs(id) ON DELETE CASCADE,
    athlete_id bigint NOT NULL,
    target text NOT NULL CHECK (target IN ('rust', 'go', 'cs')),
    attempt integer NOT NULL,
    event_type text NOT NULL CHECK (event_type IN ('paused', 'resumed')),
    waiting_reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX gateway_sync_events_job_idx ON gateway_sync_events (sync_job_id, id);

-- +goose Down
DROP TABLE gateway_sync_events;
