-- +goose Up
CREATE TABLE gateway_sync_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id bigint NOT NULL REFERENCES gateway_connections(athlete_id),
    target text NOT NULL CHECK (target IN ('rust', 'go', 'cs')),
    mode text NOT NULL CHECK (mode IN ('initial', 'incremental', 'full')),
    page integer NOT NULL DEFAULT 1 CHECK (page > 0),
    after_epoch bigint,
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'succeeded', 'dead')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX gateway_sync_jobs_active_idx ON gateway_sync_jobs (athlete_id, target)
    WHERE status IN ('queued', 'processing');
CREATE INDEX gateway_sync_jobs_due_idx ON gateway_sync_jobs (next_attempt_at, id)
    WHERE status = 'queued';

-- +goose Down
DROP TABLE gateway_sync_jobs;
