-- +goose Up
CREATE TABLE strava_webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key char(64) NOT NULL UNIQUE,
    subscription_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    object_id bigint NOT NULL,
    object_type text NOT NULL,
    aspect_type text NOT NULL,
    event_time bigint NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'processed', 'dead')),
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    attempts integer NOT NULL DEFAULT 0,
    lease_until timestamptz,
    received_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX strava_webhook_events_pending_idx
    ON strava_webhook_events (next_attempt_at, id)
    WHERE status = 'pending';

CREATE TABLE strava_delivery_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES strava_webhook_events(id) ON DELETE CASCADE,
    target text NOT NULL CHECK (target IN ('rust', 'go', 'cs')),
    status text NOT NULL CHECK (status IN ('waiting_for_fetch', 'pending', 'delivered', 'dead')),
    artifact_sha256 char(64),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, target)
);
CREATE INDEX strava_delivery_outbox_pending_idx
    ON strava_delivery_outbox (next_attempt_at, id)
    WHERE status = 'pending';

-- +goose Down
DROP TABLE strava_delivery_outbox;
DROP TABLE strava_webhook_events;
