use crate::app_error;
use crate::controllers::activities;
use crate::controllers::activity_imports;
use crate::controllers::admin;
use crate::controllers::fitness;
use crate::controllers::garmin_iq;
use crate::controllers::integration_events;
use crate::controllers::reports;
use crate::controllers::segments;
use crate::controllers::strava;
use crate::controllers::training_goals;
use crate::controllers::user_preferences;
use kaleido::auth::openapi as auth_openapi;
use kaleido::background_jobs::openapi as background_jobs_openapi;
use kaleido::glass::openapi as glass_openapi;
use kaleido::glass::SecurityAddon;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth_openapi::paths::register,
        auth_openapi::paths::login,
        auth_openapi::paths::current,
        auth_openapi::paths::refresh,
        auth_openapi::paths::logout,
        auth_openapi::paths::resend_confirmation,
        auth_openapi::paths::verify_email,
        auth_openapi::paths::forgot_password,
        auth_openapi::paths::reset_password,
        auth_openapi::paths::oauth_providers,
        auth_openapi::paths::oauth_authorize,
        auth_openapi::paths::oauth_callback,
        admin::backfill_analytics,
        admin::backfill_user_xc_training,
        admin::regenerate_segment_efforts,
        admin::regenerate_user_segments,
        admin::reprocess_activity_import,
        admin::reprocess_user_activity_imports,
        activities::list_activities,
        activities::get_activity,
        activities::update_activity,
        activities::delete_activity,
        activities::regenerate_activity,
        fitness::get_fitness_freshness,
        training_goals::get_xc_goal_progress,
        training_goals::get_dh_goal_progress,
        reports::get_training_reports,
        activity_imports::list_activity_imports,
        activity_imports::get_activity_processing_state,
        activity_imports::list_activity_archive_import_jobs,
        activity_imports::get_activity_archive_import_job,
        activity_imports::upload_activity_import,
        activity_imports::import_activity_archive_from_url,
        integration_events::list_strava_history,
        integration_events::list_admin_integration_events,
        garmin_iq::begin_link,
        garmin_iq::complete_link,
        garmin_iq::poll_link,
        garmin_iq::refresh_access_token,
        garmin_iq::list_linked_devices,
        garmin_iq::unlink_device,
        garmin_iq::sync_segments,
        strava::begin_connect,
        strava::get_connection,
        strava::queue_sync,
        strava::disconnect_connection,
        strava::handle_callback,
        strava::handle_webhook_verification,
        strava::handle_webhook_event,
        segments::list_segments,
        segments::get_segment,
        segments::update_segment,
        segments::update_segment_from_activity,
        segments::delete_segment,
        segments::import_segment,
        segments::create_segment_from_activity,
        user_preferences::get_preferences,
        user_preferences::update_preferences,
        glass_openapi::paths::public_flags,
        glass_openapi::paths::list_flags,
        glass_openapi::paths::update_flag,
        background_jobs_openapi::paths::list_tasks,
        background_jobs_openapi::paths::get_task,
        background_jobs_openapi::paths::rerun_task,
        background_jobs_openapi::paths::cancel_task,
    ),
    components(
        schemas(
            app_error::ApiErrorResponse,
            admin::AnalyticsBackfillResponse,
            admin::RegenerateSegmentEffortsRequest,
            admin::RegenerateSegmentEffortsResponse,
            admin::RegenerateUserSegmentsRequest,
            admin::RegenerateUserSegmentsResponse,
            admin::ReprocessActivityImportRequest,
            admin::ReprocessActivityImportResponse,
            admin::ReprocessUserActivityImportsRequest,
            admin::ReprocessUserActivityImportsResponse,
            crate::activity_type::ActivityType,
            crate::activity_training_analysis::ActivityRideFocus,
            crate::activity_training_analysis::ActivityTrainingAnalysisResponse,
            activities::ActivityResponse,
            activities::ActivitySegmentEffort,
            activities::UpdateActivityRequest,
            fitness::FitnessFreshnessPoint,
            fitness::FitnessFreshnessResponse,
            reports::ReportBoundary,
            reports::RideSummaryReportResponse,
            reports::TrainingReportPointResponse,
            reports::TrainingReportsResponse,
            training_goals::TrainingGoalKey,
            training_goals::TrainingMetricUnit,
            training_goals::TrainingGoalDirection,
            training_goals::TrainingRecommendationKey,
            training_goals::TrainingRecommendationPriority,
            training_goals::TrainingGoalMetricResponse,
            training_goals::TrainingRecommendationResponse,
            training_goals::XcEventProfile,
            training_goals::XcReadinessStatus,
            training_goals::XcReadinessGateKey,
            training_goals::XcTrainingDeficitKey,
            training_goals::XcTrainingPurpose,
            training_goals::XcProgressSummaryResponse,
            training_goals::XcEventGoalResponse,
            training_goals::XcReadinessSummaryResponse,
            training_goals::XcReadinessGateResponse,
            training_goals::XcTrainingDeficitResponse,
            training_goals::XcSuggestedRideResponse,
            training_goals::XcRaceResultResponse,
            training_goals::XcRideProgressResponse,
            training_goals::XcWeeklyProgressPointResponse,
            training_goals::XcGoalProgressResponse,
            training_goals::DhProgressSummaryResponse,
            training_goals::DhSegmentProgressResponse,
            training_goals::DhSessionSummaryResponse,
            training_goals::DhGoalProgressResponse,
            crate::training_profile::ActivityHeartRateZoneSummary,
            crate::activity_details::ActivityLap,
            crate::activity_details::ActivityChartPoint,
            crate::activity_details::ActivityRoutePoint,
            activity_imports::ActivityImportResponse,
            activity_imports::ActivityProcessingStateResponse,
            activity_imports::ArchiveUrlImportRequest,
            activity_imports::ActivityArchiveImportJobResponse,
            integration_events::IntegrationEventResponse,
            garmin_iq::GarminIqBeginLinkResponse,
            garmin_iq::GarminIqCompleteLinkRequest,
            garmin_iq::GarminIqCompleteLinkResponse,
            garmin_iq::GarminIqPollLinkResponse,
            garmin_iq::GarminIqRefreshResponse,
            garmin_iq::GarminIqLinkedDeviceResponse,
            garmin_iq::GarminIqSegmentSyncResponse,
            garmin_iq::GarminIqSegmentSyncItem,
            garmin_iq::GarminIqRoutePoint,
            strava::StravaAuthorizeResponse,
            strava::StravaConnectionResponse,
            crate::strava::StravaWebhookChallengeResponse,
            crate::strava::StravaWebhookEvent,
            crate::archive_import::ActivityArchiveImportResponse,
            segments::CreateSegmentFromActivityRequest,
            segments::SegmentBuilderSourceResponse,
            segments::SegmentMode,
            segments::UpdateSegmentRequest,
            segments::SegmentResponse,
            segments::SegmentEffortResponse,
            user_preferences::UserPreferencesResponse,
            user_preferences::UpdateUserPreferencesRequest,
            auth_openapi::schemas::MessageResponse,
            auth_openapi::schemas::RegisterRequest,
            auth_openapi::schemas::RegisterResponse,
            auth_openapi::schemas::LoginRequest,
            auth_openapi::schemas::ResendConfirmationRequest,
            auth_openapi::schemas::ForgotPasswordRequest,
            auth_openapi::schemas::ResetPasswordRequest,
            auth_openapi::schemas::UserResponse,
            auth_openapi::schemas::OAuthProviderMetadata,
            auth_openapi::schemas::OAuthProvidersResponse,
            glass_openapi::schemas::PublicFlagResponse,
            glass_openapi::schemas::FeatureFlagResponse,
            glass_openapi::schemas::UpdateFlagRequest,
            glass_openapi::schemas::PaginatedResponse<activities::ActivityResponse>,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::FeatureFlagResponse>,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::PublicFlagResponse>,
            kaleido::glass::data::pagination::PaginationParams,
            background_jobs_openapi::schemas::PaginatedResponse<background_jobs_openapi::schemas::TaskResponse>,
            background_jobs_openapi::schemas::PaginationMetadata,
            background_jobs_openapi::schemas::TaskResponse,
            background_jobs_openapi::schemas::TaskDetailResponse,
        )
    ),
    tags(
        (name = "activities", description = "Normalized activity list and detail endpoints"),
        (name = "fitness", description = "Training load, fitness, fatigue, and form analytics"),
        (name = "training", description = "XC and DH goals/progress analytics"),
        (name = "activity-imports", description = "Manual activity upload endpoints"),
        (name = "strava", description = "Strava OAuth connection and activity sync endpoints"),
        (name = "garmin-iq", description = "Garmin Connect IQ link, auth refresh, and segment sync endpoints"),
        (name = "segments", description = "Manual segment import and effort comparison endpoints"),
        (name = "preferences", description = "Authenticated Bike user preferences"),
        (name = "admin", description = "Admin-only endpoints"),
        (name = "auth", description = "Authentication and user management"),
        (name = "flags", description = "Feature flags"),
        (name = "oauth", description = "OAuth authentication")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
