use crate::app_error;
use crate::controllers;
use crate::controllers::activities;
use crate::controllers::activity_imports;
use crate::controllers::admin;
use crate::controllers::fitness;
use crate::controllers::integration_events;
use crate::controllers::reports;
use crate::controllers::segments;
use crate::controllers::strava;
use crate::controllers::training_goals;
use crate::controllers::user_preferences;
use kaleido::auth::openapi as auth_openapi;
use kaleido::background_jobs::openapi as background_jobs_openapi;
use kaleido::glass::openapi as glass_openapi;
use kaleido::glass::SecurityAddon;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth_openapi::paths::register,
        auth_openapi::paths::login,
        auth_openapi::paths::current,
        auth_openapi::paths::refresh,
        auth_openapi::paths::logout,
        auth_openapi::paths::resend_confirmation,
        auth_openapi::paths::verify_email,
        auth_openapi::paths::forgot_password,
        auth_openapi::paths::reset_password,
        auth_openapi::paths::oauth_providers,
        auth_openapi::paths::oauth_authorize,
        auth_openapi::paths::oauth_callback,
        auth_openapi::paths::list_users,
        auth_openapi::paths::get_user,
        auth_openapi::paths::update_user,
        auth_openapi::paths::disable_user,
        controllers::health,
        admin::app_metrics,
        admin::list_admin_activities,
        admin::get_admin_activity_import_trace,
        admin::get_admin_activity_import_trace_for_activity,
        admin::backfill_analytics,
        admin::backfill_user_xc_training,
        admin::regenerate_segment_efforts,
        admin::regenerate_user_segments,
        admin::reprocess_activity_import,
        admin::reprocess_user_activity_imports,
        admin::cleanup_user_duplicate_activities,
        admin::import_activity_archive,
        activities::list_activities,
        activities::get_activity,
        activities::update_activity,
        activities::delete_activity,
        activities::regenerate_activity,
        activities::download_activity_source_file,
        fitness::get_fitness_freshness,
        training_goals::get_xc_goal_progress,
        training_goals::get_dh_goal_progress,
        reports::get_training_report_definitions,
        reports::get_training_reports,
        activity_imports::list_activity_imports,
        activity_imports::get_activity_import_trace,
        activity_imports::get_activity_processing_graph,
        activity_imports::get_activity_processing_state,
        activity_imports::list_activity_archive_import_jobs,
        activity_imports::get_activity_archive_import_job,
        activity_imports::upload_activity_import,
        activity_imports::import_activity_archive_from_url,
        integration_events::list_strava_history,
        integration_events::list_admin_integration_events,
        strava::begin_connect,
        strava::get_connection,
        strava::queue_sync,
        strava::disconnect_connection,
        strava::handle_callback,
        strava::handle_webhook_verification,
        strava::handle_webhook_event,
        segments::list_segments,
        segments::get_segment,
        segments::get_segment_comparison,
        segments::get_segment_yearly_bests,
        segments::get_segment_effort_analysis,
        segments::update_segment,
        segments::update_segment_from_activity,
        segments::delete_segment,
        segments::import_segment,
        segments::create_segment_from_activity,
        user_preferences::get_preferences,
        user_preferences::update_preferences,
        glass_openapi::paths::public_flags,
        glass_openapi::paths::list_flags,
        glass_openapi::paths::update_flag,
        glass_openapi::paths::get_metrics,
        background_jobs_openapi::paths::list_tasks,
        background_jobs_openapi::paths::get_task,
        background_jobs_openapi::paths::rerun_task,
        background_jobs_openapi::paths::cancel_task,
    ),
    components(
        schemas(
            app_error::ApiErrorResponse,
            controllers::HealthResponse,
            admin::AdminActivityResponse,
            admin::AnalyticsBackfillResponse,
            admin::RegenerateSegmentEffortsRequest,
            admin::RegenerateSegmentEffortsResponse,
            admin::RegenerateUserSegmentsRequest,
            admin::RegenerateUserSegmentsResponse,
            admin::ReprocessActivityImportRequest,
            admin::ReprocessActivityImportResponse,
            admin::ReprocessUserActivityImportsRequest,
            admin::ReprocessUserActivityImportsResponse,
            admin::ArchiveImportRequest,
            admin::ArchiveImportResponse,
            admin::CleanupUserDuplicateActivitiesRequest,
            admin::CleanupUserDuplicateActivitiesResponse,
            bike_core::activity_type::ActivityType,
            bike_core::activity_training_analysis::ActivityRideFocus,
            bike_core::activity_training_analysis::ActivityTrainingAnalysisResponse,
            activities::ActivityResponse,
            activities::ActivitySegmentEffort,
            activities::UpdateActivityRequest,
            fitness::FitnessFreshnessPoint,
            fitness::FitnessFreshnessResponse,
            bike_core::services::reports::ReportBoundary,
            bike_core::services::reports::ReportFilterKey,
            bike_core::services::reports::ReportId,
            bike_core::services::reports::ReportMetricDirection,
            bike_core::services::reports::ClimbResponse,
            bike_core::services::reports::ClimbingReportResponse,
            bike_core::services::reports::CompareRideCandidateResponse,
            bike_core::services::reports::CompareRideColumnResponse,
            bike_core::services::reports::CompareRideMetricResponse,
            bike_core::services::reports::CompareRideMetricTrendResponse,
            bike_core::services::reports::CompareRideMetricValueResponse,
            bike_core::services::reports::CompareRidesReportResponse,
            bike_core::services::reports::EnduranceReportResponse,
            bike_core::services::reports::EnduranceRideResponse,
            bike_core::services::reports::FatigueReportResponse,
            bike_core::services::reports::FatigueRideResponse,
            bike_core::services::reports::HourlyDurabilityResponse,
            bike_core::services::reports::ReassessmentAbilityEstimateResponse,
            bike_core::services::reports::ReassessmentBenchmarkRideResponse,
            bike_core::services::reports::ReassessmentImprovementResponse,
            bike_core::services::reports::ReassessmentReportResponse,
            bike_core::services::reports::ReassessmentSignalResponse,
            bike_core::services::reports::ReassessmentTargetResponse,
            bike_core::services::reports::ReassessmentTargetSource,
            bike_core::services::reports::ReassessmentVerdict,
            bike_core::services::reports::ReassessmentWindowResponse,
            bike_core::services::reports::RideSummaryReportResponse,
            bike_core::services::reports::TrainingReportPointResponse,
            bike_core::services::reports::TrainingReportDefinitionResponse,
            bike_core::services::reports::TrainingReportDefinitionsResponse,
            bike_core::services::reports::TrainingReportMetricDefinitionResponse,
            bike_core::services::reports::TrainingReportsResponse,
            bike_core::services::training_goals::TrainingGoalKey,
            bike_core::services::training_goals::TrainingMetricUnit,
            bike_core::services::training_goals::TrainingGoalDirection,
            bike_core::services::training_goals::TrainingRecommendationKey,
            bike_core::services::training_goals::TrainingRecommendationPriority,
            bike_core::services::training_goals::TrainingGoalMetricResponse,
            bike_core::services::training_goals::TrainingRecommendationResponse,
            bike_core::services::training_goals::XcEventProfile,
            bike_core::services::training_goals::XcReadinessStatus,
            bike_core::services::training_goals::XcReadinessGateKey,
            bike_core::services::training_goals::XcTrainingDeficitKey,
            bike_core::services::training_goals::XcTrainingPurpose,
            bike_core::services::training_goals::XcProgressSummaryResponse,
            bike_core::services::training_goals::XcEventGoalResponse,
            bike_core::services::training_goals::XcReadinessSummaryResponse,
            bike_core::services::training_goals::XcReadinessGateResponse,
            bike_core::services::training_goals::XcTrainingDeficitResponse,
            bike_core::services::training_goals::XcSuggestedRideResponse,
            bike_core::services::training_goals::XcRaceResultResponse,
            bike_core::services::training_goals::XcRideProgressResponse,
            bike_core::services::training_goals::XcWeeklyProgressPointResponse,
            bike_core::services::training_goals::XcGoalProgressResponse,
            bike_core::services::training_goals::DhProgressSummaryResponse,
            bike_core::services::training_goals::DhSegmentProgressResponse,
            bike_core::services::training_goals::DhSessionSummaryResponse,
            bike_core::services::training_goals::DhGoalProgressResponse,
            bike_core::training_profile::ActivityHeartRateZoneSummary,
            bike_core::activity_details::ActivityLap,
            bike_core::activity_details::ActivityChartPoint,
            bike_core::activity_details::ActivityRoutePoint,
            activity_imports::ActivityImportResponse,
            activity_imports::ActivityImportTraceEventResponse,
            activity_imports::ActivityImportTraceNodeResponse,
            activity_imports::ActivityImportTraceResponse,
            activity_imports::ActivityProcessingGraphEdgeResponse,
            activity_imports::ActivityProcessingGraphNodeResponse,
            activity_imports::ActivityProcessingGraphResponse,
            activity_imports::ActivityProcessingStateResponse,
            activity_imports::ArchiveUrlImportRequest,
            activity_imports::ActivityArchiveImportJobResponse,
            integration_events::IntegrationEventResponse,
            strava::StravaAuthorizeResponse,
            strava::StravaConnectionResponse,
            bike_core::strava::StravaWebhookChallengeResponse,
            bike_core::strava::StravaWebhookEvent,
            bike_core::archive_import::ActivityArchiveImportResponse,
            segments::CreateSegmentFromActivityRequest,
            segments::SegmentBuilderSourceResponse,
            segments::SegmentMode,
            segments::UpdateSegmentRequest,
            segments::SegmentResponse,
            segments::SegmentComparisonResponse,
            segments::SegmentYearlyBestsResponse,
            segments::SegmentYearlyBestResponse,
            segments::SegmentEffortAnalysisQuery,
            segments::SegmentEffortAnalysisResponse,
            segments::SegmentAnalysisEffortSummaryResponse,
            segments::SegmentAnalysisSectionResponse,
            segments::SegmentAnalysisSectionEffortResponse,
            segments::SegmentEffortResponse,
            segments::SegmentRoutePointResponse,
            user_preferences::UserPreferencesResponse,
            user_preferences::UpdateUserPreferencesRequest,
            auth_openapi::schemas::MessageResponse,
            auth_openapi::schemas::RegisterRequest,
            auth_openapi::schemas::RegisterResponse,
            auth_openapi::schemas::LoginRequest,
            auth_openapi::schemas::ResendConfirmationRequest,
            auth_openapi::schemas::ForgotPasswordRequest,
            auth_openapi::schemas::ResetPasswordRequest,
            auth_openapi::schemas::UserResponse,
            auth_openapi::schemas::OAuthProviderMetadata,
            auth_openapi::schemas::OAuthProvidersResponse,
            auth_openapi::schemas::AdminUserResponse,
            auth_openapi::schemas::AdminUsersListResponse,
            auth_openapi::schemas::UpdateUserRequest,
            auth_openapi::schemas::DisableUserRequest,
            glass_openapi::schemas::PublicFlagResponse,
            glass_openapi::schemas::FeatureFlagResponse,
            glass_openapi::schemas::UpdateFlagRequest,
            glass_openapi::schemas::SystemMetrics,
            glass_openapi::schemas::PaginatedResponse<activities::ActivityResponse>,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::FeatureFlagResponse>,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::PublicFlagResponse>,
            kaleido::glass::data::pagination::PaginationParams,
            background_jobs_openapi::schemas::PaginatedResponse<background_jobs_openapi::schemas::TaskResponse>,
            background_jobs_openapi::schemas::PaginationMetadata,
            background_jobs_openapi::schemas::TaskResponse,
            background_jobs_openapi::schemas::TaskDetailResponse,
        )
    ),
    tags(
        (name = "activities", description = "Normalized activity list and detail endpoints"),
        (name = "fitness", description = "Training load, fitness, fatigue, and form analytics"),
        (name = "training", description = "XC and DH goals/progress analytics"),
        (name = "activity-imports", description = "Manual activity upload endpoints"),
        (name = "strava", description = "Strava OAuth connection and activity sync endpoints"),
        (name = "segments", description = "Manual segment import and effort comparison endpoints"),
        (name = "preferences", description = "Authenticated Bike user preferences"),
        (name = "admin", description = "Admin-only endpoints"),
        (name = "auth", description = "Authentication and user management"),
        (name = "flags", description = "Feature flags"),
        (name = "oauth", description = "OAuth authentication")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
