ARG NODE_VERSION=24.21.0
ARG NPM_VERSION=12.2.0
ARG PNPM_VERSION=12.9.1

FROM node:${NODE_VERSION}-alpine
ARG NPM_VERSION
ARG PNPM_VERSION
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm install -g "npm@${NPM_VERSION}"
RUN npm install -g "pnpm@${PNPM_VERSION}"

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY docker-entrypoint-dev.sh /usr/local/bin/docker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

COPY . .
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD ["pnpm", "run", "dev"]
