ARG NODE_ALPINE_IMAGE
ARG NPM_VERSION
ARG PNPM_VERSION

FROM ${NODE_ALPINE_IMAGE:-scratch}
ARG NPM_VERSION
ARG PNPM_VERSION
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm install -g "npm@${NPM_VERSION:?NPM_VERSION must be supplied by mise}"
RUN npm install -g --allow-scripts=pnpm "pnpm@${PNPM_VERSION:?PNPM_VERSION must be supplied by mise}"

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY docker-entrypoint-dev.sh /usr/local/bin/docker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

COPY . .
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD ["pnpm", "run", "dev"]
