use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                "CREATE TABLE oauth_states (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                state_hash varchar NOT NULL UNIQUE,
                provider varchar NOT NULL,
                nonce varchar NOT NULL,
                expires_at timestamptz NOT NULL,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX oauth_states_expires_at_idx ON oauth_states (expires_at);",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP TABLE oauth_states;")
            .await?;
        Ok(())
    }
}
